name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5a936d91f554fe0992a7ebfa34b6af07dfc35c450c9b783a8b00ea62377d453"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
