name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e13831e8ac6af28a1bf499408df22be3d2592aeb1414fc5a6a693f6d91d3a7"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
