name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b099c5960fd7c1c2cbbee4714eaa4833de71dde4e6fb21ad08de779b019527"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
