name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85cb1898c98f26c44e658a631f14a2684443d4c830e9668a0151c59cb305578a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
