name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4d5bed8e1833359f2d2f89b9318718ce755c802f6606657d3564ed4154ae6e0"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
