name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e565055883ce4e47b7a8a30ce02c940383bd657abf8e407a35bcab2f674e0af9"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
