name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a4bca55e1d33064adb1c4045bb892f03636c587c06a6a0756db8918a574199c"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
