name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a107631016fc3708bd5172ea842eb5509c703c820f082bfe7f3a3ff72f5b2b5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
