name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fa681dc53aafe43384a1c9dc9842f68a6dd43721ac70b2cc2b49621424fe50"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
