name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c70e25c4ae824973f29c77d28b97d9008aeedabee9514675ef12e92b4983bb6"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
