name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46e8f7cb3c4543a36898918cb867c9c06857603ee684ac9fdd7e77d9fc2856ed"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
