name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c4dabd6e568608a5a6e5a24e85ba6673e6a747ff2ae20337bb649fdc761a759"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
