name = "Vaulters Paradise S 3"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5caace388dc87c65c2bc83050874e3864c295ba5716f9e6578dad3de60130912"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
